server:
  port: 8092
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#引入dubbo的配置
dubbo:
  scan:
    basePackages: com.jd
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.244.10:2181?backup=192.168.244.10:2182,192.168.244.10:2183
